#!/usr/bin/env bash
set -e

# Configurar cmake si no existe la carpeta build
if [ ! -d "build" ]; then
    cmake -S . -B build -G Ninja > /dev/null 2>&1 || cmake -S . -B build > /dev/null 2>&1
fi

# Compilar y ejecutar
if cmake --build build; then
    echo ""
    ./build/tarea
fi
